# Change these first
owner: miladezzat # Your GitHub organization or username, where this repository lives
repo: InBrief # The name of this repository

# Schedule uptime checks every hour instead of default 5 minutes
schedule:
  cron: "0 * * * *"

sites:
  - name: InBrief Web
    url: https://inbrief.sh
  - name: InBrief API
    url: https://api.inbrief.sh/api/health

notifications:
  - type: email
    recipients:
      - ${{ secrets.UPPTIME_NOTIFICATION_EMAIL }}
    events:
      - down
      - degraded
      - up

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.inbrief.sh
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/miladezzat/Briefly/main/status/assets/upptime-icon.svg
  name: InBrief Status
  introTitle: "**InBrief Status** makes uptime data for InBrief services available in real time."
  introMessage: Monitor the live health of the InBrief web app and API, and let issues surface incidents so the team can respond fast.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/miladezzat/Briefly

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
